package edu.isi.bmkeg.utils
{
	import mx.collections.ArrayCollection;

	public class ColorPalette
	{
		
		public static var colors:ArrayCollection = new ArrayCollection([
			{ "label":"Blue", "color":"#0066FF" },
			{ "label":"Brown", "color":"#AF593E" },
			{ "label":"Gold", "color":"#E6BE8A" },
			{ "label":"Green", "color":"#01A368" },
			{ "label":"Green Yellow", "color":"#F1E788" },
			{ "label":"Forest Green", "color":"#5FA777" },
			{ "label":"Indigo", "color":"#4F69C6" },
			{ "label":"Magenta", "color":"#F653A6" },
			{ "label":"Navy Blue", "color":"#0066CC" },
			{ "label":"Maroon", "color":"#C32148" },
			{ "label":"Olive Green", "color":"#B5B35C" },
			{ "label":"Orange", "color":"#FF681F" },
			{ "label":"Pacific Blue", "color":"#009DC4" },
			{ "label":"Red", "color":"#ED0A3F" },
			{ "label":"Royal Purple", "color":"#6B3FA0" },
			{ "label":"Salmon", "color":"#FF91A4" },
			{ "label":"Scarlet", "color":"#FD0E35" },
			{ "label":"Silver", "color":"#C9C0BB" },
			{ "label":"Sky Blue", "color":"#76D7EA" },
			{ "label":"Spring Green", "color":"#ECEBBD" },
			{ "label":"Yellow", "color":"#FBE870" },
			{ "label":"Almond", "color":"#EED9C4" },
			{ "label":"Antique Brass", "color":"#C88A65" },
			{ "label":"Apricot", "color":"#FDD5B1" },
			{ "label":"Aquamarine", "color":"#71D9E2" },
			{ "label":"Asparagus", "color":"#7BA05B" },
			{ "label":"Atomic Tangerine", "color":"#FF9966" },
			{ "label":"Awesome", "color":"#FF2052" },
			{ "label":"Banana Mania", "color":"#FBE7B2" },
			{ "label":"Beaver", "color":"#926F5B" },
			{ "label":"Bear Hug", "color":"#6B655A" },
			{ "label":"Best Friends", "color":"#D600FF" },
			{ "label":"Bittersweet", "color":"#FE6F5E" },
			{ "label":"Blizzard Blue", "color":"#A3E3ED" },
			{ "label":"Blue Bell", "color":"#9999CC" },
			{ "label":"Blue Gray", "color":"#333366" },
			{ "label":"Blue Green", "color":"#0095B6" },
			{ "label":"Blue Violet", "color":"#6456B7" },
			{ "label":"Brick Red", "color":"#C62D42" },
			{ "label":"Brink Pink", "color":"#FB607F" },
			{ "label":"Burnt Orange", "color":"#FF7034" },
			{ "label":"Burnt Sienna", "color":"#E97451" },
			{ "label":"Cadet Blue", "color":"#A9B2C3" },
			{ "label":"Canary", "color":"#FFFF99" },
			{ "label":"Caribbean Green", "color":"#00CC99" },
			{ "label":"Carnation Pink", "color":"#FFA6C9" },
			{ "label":"Cerise", "color":"#DA3287" },
			{ "label":"Cerulean", "color":"#02A4D3" },
			{ "label":"Chartreuse", "color":"#7FFF00" },
			{ "label":"Chestnut", "color":"#B94E48" },
			{ "label":"Copper", "color":"#DA8A67" },
			{ "label":"Cornflower", "color":"#93CCEA" },
			{ "label":"Cotton Candy", "color":"#FFB7D5" },
			{ "label":"Cranberry", "color":"#DB5079" },
			{ "label":"Dandelion", "color":"#FED85D" },
			{ "label":"Denim", "color":"#1560BD" },
			{ "label":"Desert Sand", "color":"#EDC9AF" },
			{ "label":"Eggplant", "color":"#614051" },
			{ "label":"Electric Lime", "color":"#CCFF00" },
			{ "label":"Famous", "color":"#E72094" },
			{ "label":"Fern", "color":"#63B76C" },
			{ "label":"Flesh", "color":"#FFCBA4" },
			{ "label":"Fuchsia", "color":"#C154C1" },
			{ "label":"Fun in the Sun", "color":"#FF5500" },
			{ "label":"Fuzzy Wuzzy Brown", "color":"#C45655" },
			{ "label":"Giving Tree", "color":"#21E339" },
			{ "label":"Goldenrod", "color":"#FCD667" },
			{ "label":"Granny Smith Apple", "color":"#9DE093" },
			{ "label":"Gray", "color":"#8B8680" },
			{ "label":"Happy Ever After", "color":"#218EB5" },
			{ "label":"Hot Magenta", "color":"#FF00CC" },
			{ "label":"Inch Worm", "color":"#B0E313" },
			{ "label":"Indian Red", "color":"#B94E48" },
			{ "label":"Jazzberry Jam", "color":"#A50B5E" },
			{ "label":"Jungle Green", "color":"#29AB87" },
			{ "label":"Laser Lemon", "color":"#FFFF66" },
			{ "label":"Lavender", "color":"#FBAED2" },
			{ "label":"Macaroni and Cheese", "color":"#FFB97B" },
			{ "label":"Magic Mint", "color":"#AAF0D1" },
			{ "label":"Mahogany", "color":"#CA3435" },
			{ "label":"Maize", "color":"#FFCC00" },
			{ "label":"Manatee", "color":"#8D90A1" },
			{ "label":"Mango Tango", "color":"#E77200" },
			{ "label":"Mauvelous", "color":"#F091A9" },
			{ "label":"Melon", "color":"#FEBAAD" },
			{ "label":"Midnight Blue", "color":"#003366" },
			{ "label":"Mountain Meadow", "color":"#1AB385" },
			{ "label":"Mulberry", "color":"#C54B8C" },
			{ "label":"Neon Carrot", "color":"#FF9933" },
			{ "label":"Orchid", "color":"#E29CD2" },
			{ "label":"Outer Space", "color":"#2D383A" },
			{ "label":"Outrageous Orange", "color":"#FF6037" },
			{ "label":"Peach", "color":"#FFCBA4" },
			{ "label":"Periwinkle", "color":"#C3CDE6" },
			{ "label":"Pig Pink", "color":"#FDD7E4" },
			{ "label":"Pine Green", "color":"#01796F" },
			{ "label":"Pink Flamingo", "color":"#FF66FF" },
			{ "label":"Plum", "color":"#843179" },
			{ "label":"Prussian Blue", "color":"#003366" },
			{ "label":"Purple Heart", "color":"#652DC1" },
			{ "label":"Purple Mountain's Majesty", "color":"#9678B6" },
			{ "label":"Purple Pizzazz", "color":"#FF00CC" },
			{ "label":"Radical Red", "color":"#FF355E" },
			{ "label":"Raw Sienna", "color":"#D27D46" },
			{ "label":"Raw Goggin", "color":"#FF355F" },
			{ "label":"Razzle Dazzle Rose", "color":"#FF33CC" },
			{ "label":"Razzmatazz", "color":"#E30B5C" },
			{ "label":"Red Orange", "color":"#FF3F34" },
			{ "label":"Red Violet", "color":"#BB3385" },
			{ "label":"Robin's Egg Blue", "color":"#00CCCC" },
			{ "label":"Screamin' Green", "color":"#66FF66" },
			{ "label":"Sea Green", "color":"#93DFB8" },
			{ "label":"Sepia", "color":"#9E5B40" },
			{ "label":"Shadow", "color":"#837050" },
			{ "label":"Shamrock", "color":"#33CC99" },
			{ "label":"Shocking Pink", "color":"#FF6FFF" },
			{ "label":"Sunglow", "color":"#FFCC33" },
			{ "label":"Sunset Orange", "color":"#FE4C40" },
			{ "label":"Super Happy", "color":"#FFFF21" },
			{ "label":"Tan", "color":"#FA9D5A" },
			{ "label":"Tickle Me Pink", "color":"#FC80A5" },
			{ "label":"Timberwolf", "color":"#D9D6CF" },
			{ "label":"Torch Red", "color":"#FD0E35" },
			{ "label":"Tropical Rain Forest", "color":"#00755E" },
			{ "label":"Tumbleweed", "color":"#DEA681" },
			{ "label":"Turquoise Blue", "color":"#6CDAE7" },
			{ "label":"Ultra Green", "color":"#66FF66" },
			{ "label":"Ultra Orange", "color":"#FF6037" },
			{ "label":"Ultra Pink", "color":"#FF6FFF" },
			{ "label":"Ultra Red", "color":"#FD5B78" },
			{ "label":"Ultra Yellow", "color":"#FFFF66" },
			{ "label":"Unmellow Yellow", "color":"#FFFF66" },
			{ "label":"Violet (Purple)", "color":"#8359A3" },
			{ "label":"Violet Red", "color":"#F7468A" },
			{ "label":"Vivid Tangerine", "color":"#FF9980" },
			{ "label":"Vivid Violet", "color":"#803790" },
			{ "label":"Wild Blue Yonder", "color":"#7A89B8" },
			{ "label":"Wild Strawberry", "color":"#FF3399" },
			{ "label":"Wild Watermelon", "color":"#FD5B78" },
			{ "label":"Wisteria", "color":"#C9A0DC" },
			{ "label":"Yellow Green", "color":"#C5E17A" },
			{ "label":"Yellow Orange", "color":"#FFAE42" }
		] );
		
	}
}