language: java
jdk:
  - openjdk6
before_install:
  - echo "CREATE USER 'build'@'localhost' IDENTIFIED BY 'LP-U88ht';GRANT ALL PRIVILEGES ON * . * TO 'build'@'localhost';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - git clone https://github.com/BMKEG/bmkeg-parent ../bmkeg-parent